---
- name: Add required repositories
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    enabled: "{{ item.enabled | default(1) }}"
    file: "{{ item.file }}"
    state: present
    mirrorlist: "{{ item.mirrorlist }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
  become: true
  register: result_swift_repos_enable
  retries: "{{ swift_retries }}"
  delay: "{{ swift_delay }}"
  until: result_swift_repos_enable is succeeded
  loop: "{{ swift_common_repos }}"
  tags:
    - common
    - packages

- name: Enable EPEL repo
  package:
    name: epel-release
    state: present
  become: true
  register: result_epel_install
  retries: "{{ swift_retries }}"
  delay: "{{ swift_delay }}"
  until: result_epel_install is succeeded
  tags:
    - common
    - packages
