---
# common
- name: Swift common tasks
  block:
    - include_tasks: common-selinux.yml
      tags:
        - selinux

    - include_tasks: common-update.yml
      when:
        - swift_update is defined and (swift_update | bool == true)
      tags:
        - update

    - include_tasks: common-repos.yml
      tags:
        - packages

    - include_tasks: common-packages.yml
      tags:
        - packages
  tags:
    - common

# swift-prep
- name: Swift preparation
  block:
    - include_tasks: swift-hosts.yml
      tags:
        - hosts
    - include_tasks: swift-system.yml
      tags:
        - system
    - include_tasks: swift-repos.yml
      tags:
        - packages
    - include_tasks: swift-packages.yml
      tags:
        - packages
    - include_tasks: common-logging.yml
      tags:
        - logging
    - include_tasks: swift-memcached.yml
      tags:
        - memcached
    - include_tasks: swift-rsyncd.yml
      tags:
        - rsyncd
    - include_tasks: swift-config.yml
      tags:
        - config
  tags:
    - prep

# swift-rings
- name: Swift rings
  block:
    - include_tasks: swift-ring-builder.yml
    - include_tasks: swift-ring-rebalance.yml
  tags:
    - rings

# swift-disk-prepare
- include_tasks: swift-disk-prepare.yml
  tags:
    - disks
    - rings

# swift-rings-distribute
- include_tasks: swift-ring-distribute.yml
  tags:
    - rings

# swift-configure
- name: Swift rings
  block:
    - include_tasks: swift-config.yml
    - include_tasks: swift-proxy-config.yml
      tags:
        - proxy
    - include_tasks: swift-keepalived.yml
      tags:
        - keepalived
    - include_tasks: swift-account-config.yml
      tags:
        - account
    - include_tasks: swift-container-config.yml
      tags:
        - container
    - include_tasks: swift-object-config.yml
      tags:
        - object
    - include_tasks: swift-dispersion-config.yml
      tags:
        - dispersion
  tags:
    - config
    - services
