---
- name: Add required Swift repositories
  yum_repository:
    name: "{{ item }}"
    state: enabled
  become: true
  register: result_swift_repos_enable
  retries: "{{ swift_retries }}"
  delay: "{{ swift_delay }}"
  until: result_swift_repos_enable is succeeded
  loop: "{{ swift_repos }}"
  tags:
    - packages
    - prep
