---
- name: Delete account rings
  file:
    path: /etc/swift/{{ item.key }}.ring.gz
    state: absent
  become: true
  become_user: "{{ swift_user }}"
  with_dict: "{{ swift_account_rings }}"

- name: Delete container rings
  file:
    path: /etc/swift/{{ item.key }}.ring.gz
    state: absent
  become: true
  become_user: "{{ swift_user }}"
  with_dict: "{{ swift_container_rings }}"

- name: Delete object rings
  file:
    path: /etc/swift/{{ item.key }}.ring.gz
    state: absent
  become: true
  become_user: "{{ swift_user }}"
  with_dict: "{{ swift_object_rings }}"

- name: Delete account builder
  file:
    path: /etc/swift/{{ item.key }}.builder
    state: absent
  become: true
  become_user: "{{ swift_user }}"
  with_dict: "{{ swift_account_rings }}"

- name: Delete container builder
  file:
    path: /etc/swift/{{ item.key }}.builder
    state: absent
  become: true
  become_user: "{{ swift_user }}"
  with_dict: "{{ swift_container_rings }}"

- name: Delete object builders
  file:
    path: /etc/swift/{{ item.key }}.builder
    state: absent
  become: true
  become_user: "{{ swift_user }}"
  with_dict: "{{ swift_object_rings }}"
