---
- name: Configure Swift dispersion tool
  template:
    src: swift-dispersion.conf.j2
    dest: /etc/swift/dispersion.conf
    mode: 0640
    owner: "{{ swift_user }}"
    group: "{{ swift_group }}"
    backup: true
  become: true
  when:
    - "inventory_hostname in groups['swift_admin']"
  tags:
    - dispersion
    - services
