---
- name: Swift ring distribute
  block:
    - name: Push account ring to cluster
      synchronize:
        src: /etc/swift/{{ item.key }}.ring.gz
        dest: /etc/swift/{{ item.key }}.ring.gz
      with_dict: "{{ swift_account_rings }}"
      delegate_to: "{{ groups['swift_admin'][0] }}"
      become: true
      when:
        - "inventory_hostname in groups['swift_account'] or inventory_hostname in groups['swift_container'] or inventory_hostname in groups['swift_object']"

    - name: Push container ring to cluster
      synchronize:
        src: /etc/swift/{{ item.key }}.ring.gz
        dest: /etc/swift/{{ item.key }}.ring.gz
      with_dict: "{{ swift_container_rings }}"
      delegate_to: "{{ groups['swift_admin'][0] }}"
      become: true
      when:
        - "inventory_hostname in groups['swift_account'] or inventory_hostname in groups['swift_container'] or inventory_hostname in groups['swift_object']"

    - name: Push object rings to cluster
      synchronize:
        src: /etc/swift/{{ item.key }}.ring.gz
        dest: /etc/swift/{{ item.key }}.ring.gz
      with_dict: "{{ swift_object_rings }}"
      delegate_to: "{{ groups['swift_admin'][0] }}"
      become: true
      when:
        - "inventory_hostname in groups['swift_account'] or inventory_hostname in groups['swift_container'] or inventory_hostname in groups['swift_object']"
  tags:
    - rings
