---
- name: Disk prepare
  block:
    - name: Match disk on node to Swift ID
      shell:
        cmd: swift-ring-builder /etc/swift/{{ item }}.builder search --region 1 --zone 1 --ip {{ swift_cluster_ip }} |grep -v Devices | awk '{print $1,$8,$NF}'
      delegate_to: "{{ groups['swift_admin'][0] }}"
      become: true
      become_user: "{{ swift_user }}"
      register: res_swift_devices
      changed_when: false
      when:
        - "inventory_hostname in groups['swift_account'] or inventory_hostname in groups['swift_container'] or inventory_hostname in groups['swift_object']"
      with_items:
        - account
        - container
        - object

    - name: Gather all disks in a list
      set_fact:
        swift_disks_list: "{{ (swift_disks_list | default([]) + item.stdout_lines) |unique }}"
        cacheable: yes
      when:
        - "inventory_hostname in groups['swift_account'] or inventory_hostname in groups['swift_container'] or inventory_hostname in groups['swift_object']"
      with_items: "{{ res_swift_devices.results }}"

    - name: Ensure directory exists for disks
      file:
        path: "/srv/node"
        state: directory
        owner: "{{ swift_user }}"
        group: "{{ swift_group }}"
        mode: 0770
      become: true
      when:
        - "inventory_hostname in groups['swift_account'] or inventory_hostname in groups['swift_container'] or inventory_hostname in groups['swift_object']"

    # This should be each device id
    - name: Ensure directory exists for each disk
      file:
        path: "/srv/node/{{ item.split()[1] }}"
        state: directory
        owner: "{{ swift_user }}"
        group: "{{ swift_group }}"
        mode: 0770
      become: true
      with_items: "{{ swift_disks_list }}"
      when:
        - "inventory_hostname in groups['swift_account'] or inventory_hostname in groups['swift_container'] or inventory_hostname in groups['swift_object']"

    # format the disk if not already formatted
    # use the id to look up the device
    # label should be 'd' + <id>
    - name: Format disks
      filesystem:
        fstype: xfs
        force: false
        dev: "{{ swift_devices[item.split()[0] | int]['disk'] }}"
        opts: "-d sunit=512,swidth=512 -L {{ item.split()[1][-12:] }}"
      become: true
      with_items: "{{ swift_disks_list }}"
      when:
        - "inventory_hostname in groups['swift_account'] or inventory_hostname in groups['swift_container'] or inventory_hostname in groups['swift_object']"

    # mount the disk
    - name: Mount the drives
      mount:
        path: "/srv/node/{{ 'd' + item.split()[0] }}"
        src: "LABEL={{ item.split()[1][-12:] }}"
        fstype: "{{ swift_disk_filesystem }}"
        state: mounted
        opts: "{% for option in swift_disk_mount_options + (swift_devices[item.split()[0] | int]['mount_options'] | default([])) %}{{ option }}{% if not loop.last %},{% endif %}{% endfor %}"
      become: true
      with_items: "{{ swift_disks_list }}"
      when:
        - "inventory_hostname in groups['swift_account'] or inventory_hostname in groups['swift_container'] or inventory_hostname in groups['swift_object']"

    - name: Ensure permissions on each disk mount
      file:
        path: "/srv/node/{{ 'd' + item.split()[0] }}"
        state: directory
        owner: "{{ swift_user }}"
        group: "{{ swift_group }}"
        mode: 0770
      become: true
      with_items: "{{ swift_disks_list }}"
      when:
        - "inventory_hostname in groups['swift_account'] or inventory_hostname in groups['swift_container'] or inventory_hostname in groups['swift_object']"

    # if fail, do we take it out of the ring?
    # you can push the ring and rebalance
  tags:
    - disks
    - rings
